/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:df1dbc4f-6837-4abe-81a9-d7be8f3af101",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_tjKkFq6Va",
    "aws_user_pools_web_client_id": "62gvb3uqa3o03d57v2jpa2lb0e",
    "oauth": {}
};


export default awsmobile;
